

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
 
mySidebar1: [
            {
            type: 'autogenerated',
            dirName: 'docs/manual', 
            },
          ],
mySidebar2: [
            {
              type: 'autogenerated',
              dirName: 'docs/user', 
            },
            ],
       
  };


module.exports = sidebars;
